IMAGENET_PROMPT = [
        "a bad photo of a {}.",
        "a photo of many {}.",
        "a sculpture of a {}.",
        "a photo of the hard to see {}.",
        "a low resolution photo of the {}.",
        "a rendering of a {}.",
        "graffiti of a {}.",
        "a bad photo of the {}.",
        "a cropped photo of the {}.",
        "a tattoo of a {}.",
        "the embroidered {}.",
        "a photo of a hard to see {}.",
        "a bright photo of a {}.",
        "a photo of a clean {}.",
        "a photo of a dirty {}.",
        "a dark photo of the {}.",
        "a drawing of a {}.",
        "a photo of my {}.",
        "the plastic {}.",
        "a photo of the cool {}.",
        "a close-up photo of a {}.",
        "a black and white photo of the {}.",
        "a painting of the {}.",
        "a painting of a {}.",
        "a pixelated photo of the {}.",
        "a sculpture of the {}.",
        "a bright photo of the {}.",
        "a cropped photo of a {}.",
        "a plastic {}.",
        "a photo of the dirty {}.",
        "a jpeg corrupted photo of a {}.",
        "a blurry photo of the {}.",
        "a photo of the {}.",
        "a good photo of the {}.",
        "a rendering of the {}.",
        "a {} in a video game.",
        "a photo of one {}.",
        "a doodle of a {}.",
        "a close-up photo of the {}.",
        "a photo of a {}.",
        "the origami {}.",
        "the {} in a video game.",
        "a sketch of a {}.",
        "a doodle of the {}.",
        "a origami {}.",
        "a low resolution photo of a {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "a photo of the clean {}.",
        "a photo of a large {}.",
        "a rendition of a {}.",
        "a photo of a nice {}.",
        "a photo of a weird {}.",
        "a blurry photo of a {}.",
        "a cartoon {}.",
        "art of a {}.",
        "a sketch of the {}.",
        "a embroidered {}.",
        "a pixelated photo of a {}.",
        "itap of the {}.",
        "a jpeg corrupted photo of the {}.",
        "a good photo of a {}.",
        "a plushie {}.",
        "a photo of the nice {}.",
        "a photo of the small {}.",
        "a photo of the weird {}.",
        "the cartoon {}.",
        "art of the {}.",
        "a drawing of the {}.",
        "a photo of the large {}.",
        "a black and white photo of a {}.",
        "the plushie {}.",
        "a dark photo of a {}.",
        "itap of a {}.",
        "graffiti of the {}.",
        "a toy {}.",
        "itap of my {}.",
        "a photo of a cool {}.",
        "a photo of a small {}.",
        "a tattoo of the {}.",
    ]

IMAGENET_PROMPT = [
        "a bad photo of a {}, which is a type of zooplankton.",
        "a photo of many {}, which is a type of zooplankton.",
        "a sculpture of a {}, which is a type of zooplankton.",
        "a photo of the hard to see {}, which is a type of zooplankton.",
        "a low resolution photo of the {}, which is a type of zooplankton.",
        "a rendering of a {}, which is a type of zooplankton.",
        "graffiti of a {}, which is a type of zooplankton.",
        "a bad photo of the {}, which is a type of zooplankton.",
        "a cropped photo of the {}, which is a type of zooplankton.",
        "a tattoo of a {}, which is a type of zooplankton.",
        "the embroidered {}, which is a type of zooplankton.",
        "a photo of a hard to see {}, which is a type of zooplankton.",
        "a bright photo of a {}, which is a type of zooplankton.",
        "a photo of a clean {}, which is a type of zooplankton.",
        "a photo of a dirty {}, which is a type of zooplankton.",
        "a dark photo of the {}, which is a type of zooplankton.",
        "a drawing of a {}, which is a type of zooplankton.",
        "a photo of my {}, which is a type of zooplankton.",
        "the plastic {}, which is a type of zooplankton.",
        "a photo of the cool {}, which is a type of zooplankton.",
        "a close-up photo of a {}, which is a type of zooplankton.",
        "a black and white photo of the {}, which is a type of zooplankton.",
        "a painting of the {}, which is a type of zooplankton.",
        "a painting of a {}, which is a type of zooplankton.",
        "a pixelated photo of the {}, which is a type of zooplankton.",
        "a sculpture of the {}, which is a type of zooplankton.",
        "a bright photo of the {}, which is a type of zooplankton.",
        "a cropped photo of a {}, which is a type of zooplankton.",
        "a plastic {}, which is a type of zooplankton.",
        "a photo of the dirty {}, which is a type of zooplankton.",
        "a jpeg corrupted photo of a {}, which is a type of zooplankton.",
        "a blurry photo of the {}, which is a type of zooplankton.",
        "a photo of the {}, which is a type of zooplankton.",
        "a good photo of the {}, which is a type of zooplankton.",
        "a rendering of the {}, which is a type of zooplankton.",
        "a {} in a video game, which is a type of zooplankton.",
        "a photo of one {}, which is a type of zooplankton.",
        "a doodle of a {}, which is a type of zooplankton.",
        "a close-up photo of the {}, which is a type of zooplankton.",
        "a photo of a {}, which is a type of zooplankton.",
        "the origami {}, which is a type of zooplankton.",
        "the {} in a video game, which is a type of zooplankton.",
        "a sketch of a {}, which is a type of zooplankton.",
        "a doodle of the {}, which is a type of zooplankton.",
        "a origami {}, which is a type of zooplankton.",
        "a low resolution photo of a {}, which is a type of zooplankton.",
        "the toy {}, which is a type of zooplankton.",
        "a rendition of the {}, which is a type of zooplankton.",
        "a photo of the clean {}, which is a type of zooplankton.",
        "a photo of a large {}, which is a type of zooplankton.",
        "a rendition of a {}, which is a type of zooplankton.",
        "a photo of a nice {}, which is a type of zooplankton.",
        "a photo of a weird {}, which is a type of zooplankton.",
        "a blurry photo of a {}, which is a type of zooplankton.",
        "a cartoon {}, which is a type of zooplankton.",
        "art of a {}, which is a type of zooplankton.",
        "a sketch of the {}, which is a type of zooplankton.",
        "a embroidered {}, which is a type of zooplankton.",
        "a pixelated photo of a {}, which is a type of zooplankton.",
        "itap of the {}, which is a type of zooplankton.",
        "a jpeg corrupted photo of the {}, which is a type of zooplankton.",
        "a good photo of a {}, which is a type of zooplankton.",
        "a plushie {}, which is a type of zooplankton.",
        "a photo of the nice {}, which is a type of zooplankton.",
        "a photo of the small {}, which is a type of zooplankton.",
        "a photo of the weird {}, which is a type of zooplankton.",
        "the cartoon {}, which is a type of zooplankton.",
        "art of the {}, which is a type of zooplankton.",
        "a drawing of the {}, which is a type of zooplankton.",
        "a photo of the large {}, which is a type of zooplankton.",
        "a black and white photo of a {}, which is a type of zooplankton.",
        "the plushie {}, which is a type of zooplankton.",
        "a dark photo of a {}, which is a type of zooplankton.",
        "itap of a {}, which is a type of zooplankton.",
        "graffiti of the {}, which is a type of zooplankton.",
        "a toy {}, which is a type of zooplankton.",
        "itap of my {}, which is a type of zooplankton.",
        "a photo of a cool {}, which is a type of zooplankton.",
        "a photo of a small {}, which is a type of zooplankton.",
        "a tattoo of the {}, which is a type of zooplankton.",
    ]